-- Seed Demo User
-- Note: This creates a demo user in the auth system
-- You'll need to run this script and then use the credentials below to log in

-- Demo User Credentials:
-- Email: demo@farmwise.com
-- Password: demo123456

-- Fixed column name from 'name' to 'org_name' and 'type' to 'org_type'
-- Insert demo organization
INSERT INTO organizations (id, org_name, org_type, contact_email, contact_phone)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'Demo Organization',
  'cooperative',
  'demo@farmwise.com',
  '+1234567890'
) ON CONFLICT (id) DO NOTHING;

-- Note: The actual auth user must be created through Supabase Auth
-- You can do this by:
-- 1. Using the demo user creator page at /auth/create-demo-user
-- 2. OR going to your Supabase Dashboard → Authentication → Users
--    Click "Add User" and create:
--    Email: demo@farmwise.com
--    Password: demo123456
--    Auto Confirm User: YES (check this box)
-- 
-- OR use the sign-up page and confirm the email

-- Insert demo user profile (this will be linked after auth user is created)
-- The user_id will need to match the UUID generated by Supabase Auth
